---
apiVersion: v1
kind: Service
metadata:
  name: groom-service
  namespace: ambassador
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: groom-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: groom-service
  namespace: ambassador
spec:
  replicas: 2
  selector:
    matchLabels:
      app: groom-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: groom-service
    spec:
      containers:
      - name: groom
        image: confederacie/groom-service
        ports:
        - name: http
          containerPort: 5000


