---
apiVersion: v1
kind: Service
metadata:
  name: user-auth
  namespace: ambassador
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: user-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth
  namespace: ambassador
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-auth
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
      - name: user-auth
        image: confederacie/user-auth
        ports:
        - name: http
          containerPort: 5000


